[package]
name = "synchronize-images"
version = "0.1.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
failure = "0.1"
lazy_static = "1.3"
regex = "1.1"
